name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Create Android project
        run: |
          mkdir www
          cp Index.html www/index.html

          npm init -y
          npm install @capacitor/core @capacitor/cli @capacitor/android

          npx cap init "Car Racing Game" "com.tikenkumar.carracing" --web-dir=www
          npx cap add android
          npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build AAB
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew bundleRelease

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: car-racing-aab
          path: android/app/build/outputs/bundle/release/*.aab
